In [ ]:
from dlt.sources.helpers.rest_client import RESTClient
from dlt.sources.helpers.rest_client.auth import BearerTokenAuth
from dlt.sources.helpers.rest_client.paginators import JSONLinkPaginator


BASE_URL = "https://api.github.com/repos/DataTalksClub/data-engineering-zoomcamp"
API_TOKEN = "Your Token"

client = RESTClient(
    base_url=BASE_URL,
    # auth=BearerTokenAuth(token=API_TOKEN), if you use token then use this line
    paginator = JSONLinkPaginator(next_url_path="next")    
)

for page in client.paginate("/events"):
    print(page)

:

In [ ]:
load_dotenv()

logger = logging.getLogger(__name__)

class AIEnrichmentService:

    def __init__(self):
        self.llm = AzureChatOpenAI(
            azure_endpoint=os.getenv("AZURE_LLM_ENDPOINT"), # Azure endpoint
            api_key=os.getenv("AZURE_LLM_KEY"), # Azure key
            api_version=os.getenv("AZURE_LLM_VERSION_4"), # API version
            deployment_name=os.getenv("AZURE_LLM_GPT4oM"), # GPT deployment
            temperature=0
        )

    def generate_summary(self, text):
        prompt = f"Summarize this article in one short sentence:\n{text}" # LLM prompt
        response = self.llm.invoke([HumanMessage(content=prompt)]) # LLM request

        return response.content # Return AI response

df["ai_summary"] = df["body"].apply(self.ai_service.generate_summary) # AI enrichment

DLT Resource - it yields the data

In [5]:
from dlt.sources.helpers.rest_client import RESTClient
from dlt.sources.helpers.rest_client.auth import BearerTokenAuth
from dlt.sources.helpers.rest_client.paginators import JSONLinkPaginator
# This library added
import dlt

BASE_URL = "https://api.github.com/repos/DataTalksClub/data-engineering-zoomcamp"
API_TOKEN = "Your Token"
MAX_PAGES_TO_READ = 10

@dlt.resource(name="events")
def paginator_geteer():
    client = RESTClient(
        base_url=BASE_URL,
        # auth=BearerTokenAuth(token=API_TOKEN), if you use token then use this line
        paginator = JSONLinkPaginator(next_url_path="next")    
    )

    for page_number, page in enumerate(client.paginate("/events"), start=1):
        if page_number > MAX_PAGES_TO_READ:
            break
        for record in page:
            yield record

for record in paginator_geteer():
    print(record)

{'id': '9288884998', 'type': 'WatchEvent', 'actor': {'id': 45904221, 'login': 'CRK1918', 'display_login': 'CRK1918', 'gravatar_id': '', 'url': 'https://api.github.com/users/CRK1918', 'avatar_url': 'https://avatars.githubusercontent.com/u/45904221?'}, 'repo': {'id': 419661684, 'name': 'DataTalksClub/data-engineering-zoomcamp', 'url': 'https://api.github.com/repos/DataTalksClub/data-engineering-zoomcamp'}, 'payload': {'action': 'started'}, 'public': True, 'created_at': '2026-05-10T20:03:28Z', 'org': {'id': 72699292, 'login': 'DataTalksClub', 'gravatar_id': '', 'url': 'https://api.github.com/orgs/DataTalksClub', 'avatar_url': 'https://avatars.githubusercontent.com/u/72699292?'}}
{'id': '9288775541', 'type': 'ForkEvent', 'actor': {'id': 39532049, 'login': 'lexiemeow', 'display_login': 'lexiemeow', 'gravatar_id': '', 'url': 'https://api.github.com/users/lexiemeow', 'avatar_url': 'https://avatars.githubusercontent.com/u/39532049?'}, 'repo': {'id': 419661684, 'name': 'DataTalksClub/data-engineering-zoomcamp', 'url': 'https://api.github.com/repos/DataTalksClub/data-engineering-zoomcamp'}, 'payload': {'action': 'forked', 'forkee': {'id': 1234911512, 'node_id': 'R_kgDOSZtBGA', 'name': 'DE-zoomcamp', 'full_name': 'lexiemeow/DE-zoomcamp', 'private': False, 'owner': {'login': 'lexiemeow', 'id': 39532049, 'node_id': 'MDQ6VXNlcjM5NTMyMDQ5', 'avatar_url': 'https://avatars.githubusercontent.com/u/39532049?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lexiemeow', 'html_url': 'https://github.com/lexiemeow', 'followers_url': 'https://api.github.com/users/lexiemeow/followers', 'following_url': 'https://api.github.com/users/lexiemeow/following{/other_user}', 'gists_url': 'https://api.github.com/users/lexiemeow/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lexiemeow/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lexiemeow/subscriptions', 'organizations_url': 'https://api.github.com/users/lexiemeow/orgs', 'repos_url': 'https://api.github.com/users/lexiemeow/repos', 'events_url': 'https://api.github.com/users/lexiemeow/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lexiemeow/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'html_url': 'https://github.com/lexiemeow/DE-zoomcamp', 'description': 'Data Engineering Zoomcamp is a free 9-week course on building production-ready data pipelines. The next cohort starts in January 2026. Join the course here 👇🏼', 'fork': True, 'url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp', 'forks_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/forks', 'keys_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/keys{/key_id}', 'collaborators_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/collaborators{/collaborator}', 'teams_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/teams', 'hooks_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/hooks', 'issue_events_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/issues/events{/number}', 'events_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/events', 'assignees_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/assignees{/user}', 'branches_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/branches{/branch}', 'tags_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/tags', 'blobs_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/git/blobs{/sha}', 'git_tags_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/git/tags{/sha}', 'git_refs_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/git/refs{/sha}', 'trees_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/git/trees{/sha}', 'statuses_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/statuses/{sha}', 'languages_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/languages', 'stargazers_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/stargazers', 'contributors_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/contributors', 'subscribers_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/subscribers', 'subscription_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/subscription', 'commits_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/commits{/sha}', 'git_commits_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/git/commits{/sha}', 'comments_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/comments{/number}', 'issue_comment_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/issues/comments{/number}', 'contents_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/contents/{+path}', 'compare_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/compare/{base}...{head}', 'merges_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/merges', 'archive_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/{archive_format}{/ref}', 'downloads_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/downloads', 'issues_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/issues{/number}', 'pulls_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/pulls{/number}', 'milestones_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/milestones{/number}', 'notifications_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/notifications{?since,all,participating}', 'labels_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/labels{/name}', 'releases_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/releases{/id}', 'deployments_url': 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/deployments', 'created_at': '2026-05-10T19:54:23Z', 'updated_at': '2026-05-10T19:54:24Z', 'pushed_at': '2026-05-03T09:21:31Z', 'git_url': 'git://github.com/lexiemeow/DE-zoomcamp.git', 'ssh_url': 'git@github.com:lexiemeow/DE-zoomcamp.git', 'clone_url': 'https://github.com/lexiemeow/DE-zoomcamp.git', 'svn_url': 'https://github.com/lexiemeow/DE-zoomcamp', 'homepage': 'https://airtable.com/appzbS8Pkg9PL254a/shr6oVXeQvSI5HuWD', 'size': 10048, 'stargazers_count': 0, 'watchers_count': 0, 'language': None, 'has_issues': False, 'has_projects': True, 'has_downloads': True, 'has_wiki': True, 'has_pages': False, 'has_discussions': False, 'forks_count': 0, 'mirror_url': None, 'archived': False, 'disabled': False, 'open_issues_count': 0, 'license': None, 'allow_forking': True, 'is_template': False, 'web_commit_signoff_required': False, 'has_pull_requests': True, 'pull_request_creation_policy': 'all', 'topics': [], 'visibility': 'public', 'forks': 0, 'open_issues': 0, 'watchers': 0, 'default_branch': 'main'}}, 'public': True, 'created_at': '2026-05-10T19:54:23Z', 'org': {'id': 72699292, 'login': 'DataTalksClub', 'gravatar_id': '', 'url': 'https://api.github.com/orgs/DataTalksClub', 'avatar_url': 'https://avatars.githubusercontent.com/u/72699292?'}}
{'id': '9287871995', 'type': 'WatchEvent', 'actor': {'id': 256124002, 'login': 'ederson-data', 'display_login': 'ederson-data', 'gravatar_id': '', 'url': 'https://api.github.com/users/ederson-data', 'avatar_url': 'https://avatars.githubusercontent.com/u/256124002?'}, 'repo': {'id': 419661684, 'name': 'DataTalksClub/data-engineering-zoomcamp', 'url': 'https://api.github.com/repos/DataTalksClub/data-engineering-zoomcamp'}, 'payload': {'action': 'started'}, 'public': True, 'created_at': '2026-05-10T18:39:31Z', 'org': {'id': 72699292, 'login': 'DataTalksClub', 'gravatar_id': '', 'url': 'https://api.github.com/orgs/DataTalksClub', 'avatar_url': 'https://avatars.githubusercontent.com/u/72699292?'}}
{'id': '9287863593', 'type': 'WatchEvent', 'actor': {'id': 112778033, 'login': 'AbdalaOs', 'display_login': 'AbdalaOs', 'gravatar_id': '', 'url': 'https://api.github.com/users/AbdalaOs', 'avatar_url': 'https://avatars.githubusercontent.com/u/112778033?'}, 'repo': {'id': 419661684, 'name': 'DataTalksClub/data-engineering-zoomcamp', 'url': 'https://api.github.com/repos/DataTalksClub/data-engineering-zoomcamp'}, 'payload': {'action': 'started'}, 'public': True, 'created_at': '2026-05-10T18:38:51Z', 'org': {'id': 72699292, 'login': 'DataTalksClub', 'gravatar_id': '', 'url': 'https://api.github.com/orgs/DataTalksClub', 'avatar_url': 'https://avatars.githubusercontent.com/u/72699292?'}}
{'id': '9287162371', 'type': 'WatchEvent', 'actor': {'id': 39532049, 'login': 'lexiemeow', 'display_login': 'lexiemeow', 'gravatar_id': '', 'url': 'https://api.github.com/users/lexiemeow', 'avatar_url': 'https://avatars.githubusercontent.com/u/39532049?'}, 'repo': {'id': 419661684, 'name': 'DataTalksClub/data-engineering-zoomcamp', 'url': 'https://api.github.com/repos/DataTalksClub/data-engineering-zoomcamp'}, 'payload': {'action': 'started'}, 'public': True, 'created_at': '2026-05-10T17:41:25Z', 'org': {'id': 72699292, 'login': 'DataTalksClub', 'gravatar_id': '', 'url': 'https://api.github.com/orgs/DataTalksClub', 'avatar_url': 'https://avatars.githubusercontent.com/u/72699292?'}}
{'id': '9286926968', 'type': 'ForkEvent', 'actor': {'id': 13960455, 'login': 'bmvsprasad', 'display_login': 'bmvsprasad', 'gravatar_id': '', 'url': 'https://api.github.com/users/bmvsprasad', 'avatar_url': 'https://avatars.githubusercontent.com/u/13960455?'}, 'repo': {'id': 419661684, 'name': 'DataTalksClub/data-engineering-zoomcamp', 'url': 'https://api.github.com/repos/DataTalksClub/data-engineering-zoomcamp'}, 'payload': {'action': 'forked', 'forkee': {'id': 1234818959, 'node_id': 'R_kgDOSZnXjw', 'name': 'data-engineering-zoomcamp', 'full_name': 'bmvsprasad/data-engineering-zoomcamp', 'private': False, 'owner': {'login': 'bmvsprasad', 'id': 13960455, 'node_id': 'MDQ6VXNlcjEzOTYwNDU1', 'avatar_url': 'https://avatars.githubusercontent.com/u/13960455?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/bmvsprasad', 'html_url': 'https://github.com/bmvsprasad', 'followers_url': 'https://api.github.com/users/bmvsprasad/followers', 'following_url': 'https://api.github.com/users/bmvsprasad/following{/other_user}', 'gists_url': 'https://api.github.com/users/bmvsprasad/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/bmvsprasad/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/bmvsprasad/subscriptions', 'organizations_url': 'https://api.github.com/users/bmvsprasad/orgs', 'repos_url': 'https://api.github.com/users/bmvsprasad/repos', 'events_url': 'https://api.github.com/users/bmvsprasad/events{/privacy}', 'received_events_url': 'https://api.github.com/users/bmvsprasad/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'html_url': 'https://github.com/bmvsprasad/data-engineering-zoomcamp', 'description': 'Data Engineering Zoomcamp is a free 9-week course on building production-ready data pipelines. The next cohort starts in January 2026. Join the course here 👇🏼', 'fork': True, 'url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp', 'forks_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/forks', 'keys_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/keys{/key_id}', 'collaborators_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/collaborators{/collaborator}', 'teams_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/teams', 'hooks_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/hooks', 'issue_events_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/issues/events{/number}', 'events_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/events', 'assignees_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/assignees{/user}', 'branches_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/branches{/branch}', 'tags_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/tags', 'blobs_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/git/blobs{/sha}', 'git_tags_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/git/tags{/sha}', 'git_refs_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/git/refs{/sha}', 'trees_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/git/trees{/sha}', 'statuses_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/statuses/{sha}', 'languages_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/languages', 'stargazers_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/stargazers', 'contributors_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/contributors', 'subscribers_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/subscribers', 'subscription_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/subscription', 'commits_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/commits{/sha}', 'git_commits_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/git/commits{/sha}', 'comments_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/comments{/number}', 'issue_comment_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/issues/comments{/number}', 'contents_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/contents/{+path}', 'compare_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/compare/{base}...{head}', 'merges_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/merges', 'archive_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/{archive_format}{/ref}', 'downloads_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/downloads', 'issues_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/issues{/number}', 'pulls_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/pulls{/number}', 'milestones_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/milestones{/number}', 'notifications_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/notifications{?since,all,participating}', 'labels_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/labels{/name}', 'releases_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/releases{/id}', 'deployments_url': 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/deployments', 'created_at': '2026-05-10T17:21:58Z', 'updated_at': '2026-05-10T17:21:59Z', 'pushed_at': '2026-05-03T09:21:31Z', 'git_url': 'git://github.com/bmvsprasad/data-engineering-zoomcamp.git', 'ssh_url': 'git@github.com:bmvsprasad/data-engineering-zoomcamp.git', 'clone_url': 'https://github.com/bmvsprasad/data-engineering-zoomcamp.git', 'svn_url': 'https://github.com/bmvsprasad/data-engineering-zoomcamp', 'homepage': 'https://airtable.com/appzbS8Pkg9PL254a/shr6oVXeQvSI5HuWD', 'size': 10048, 'stargazers_count': 0, 'watchers_count': 0, 'language': None, 'has_issues': False, 'has_projects': True, 'has_downloads': True, 'has_wiki': True, 'has_pages': False, 'has_discussions': False, 'forks_count': 0, 'mirror_url': None, 'archived': False, 'disabled': False, 'open_issues_count': 0, 'license': None, 'allow_forking': True, 'is_template': False, 'web_commit_signoff_required': False, 'has_pull_requests': True, 'pull_request_creation_policy': 'all', 'topics': [], 'visibility': 'public', 'forks': 0, 'open_issues': 0, 'watchers': 0, 'default_branch': 'main'}}, 'public': True, 'created_at': '2026-05-10T17:21:58Z', 'org': {'id': 72699292, 'login': 'DataTalksClub', 'gravatar_id': '', 'url': 'https://api.github.com/orgs/DataTalksClub', 'avatar_url': 'https://avatars.githubusercontent.com/u/72699292?'}}
{'id': '9286533726', 'type': 'WatchEvent', 'actor': {'id': 281697474, 'login': 'malkiwalid', 'display_login': 'malkiwalid', 'gravatar_id': '', 'url': 'https://api.github.com/users/malkiwalid', 'avatar_url': 'https://avatars.githubusercontent.com/u/281697474?'}, 'repo': {'id': 419661684, 'name': 'DataTalksClub/data-engineering-zoomcamp', 'url': 'https://api.github.com/repos/DataTalksClub/data-engineering-zoomcamp'}, 'payload': {'action': 'started'}, 'public': True, 'created_at': '2026-05-10T16:49:40Z', 'org': {'id': 72699292, 'login': 'DataTalksClub', 'gravatar_id': '', 'url': 'https://api.github.com/orgs/DataTalksClub', 'avatar_url': 'https://avatars.githubusercontent.com/u/72699292?'}}
{'id': '9285933558', 'type': 'WatchEvent', 'actor': {'id': 152066777, 'login': 'AboidoLiven', 'display_login': 'AboidoLiven', 'gravatar_id': '', 'url': 'https://api.github.com/users/AboidoLiven', 'avatar_url': 'https://avatars.githubusercontent.com/u/152066777?'}, 'repo': {'id': 419661684, 'name': 'DataTalksClub/data-engineering-zoomcamp', 'url': 'https://api.github.com/repos/DataTalksClub/data-engineering-zoomcamp'}, 'payload': {'action': 'started'}, 'public': True, 'created_at': '2026-05-10T16:02:51Z', 'org': {'id': 72699292, 'login': 'DataTalksClub', 'gravatar_id': '', 'url': 'https://api.github.com/orgs/DataTalksClub', 'avatar_url': 'https://avatars.githubusercontent.com/u/72699292?'}}
{'id': '9285651299', 'type': 'WatchEvent', 'actor': {'id': 161979467, 'login': 'bensam-dan', 'display_login': 'bensam-dan', 'gravatar_id': '', 'url': 'https://api.github.com/users/bensam-dan', 'avatar_url': 'https://avatars.githubusercontent.com/u/161979467?'}, 'repo': {'id': 419661684, 'name': 'DataTalksClub/data-engineering-zoomcamp', 'url': 'https://api.github.com/repos/DataTalksClub/data-engineering-zoomcamp'}, 'payload': {'action': 'started'}, 'public': True, 'created_at': '2026-05-10T15:40:00Z', 'org': {'id': 72699292, 'login': 'DataTalksClub', 'gravatar_id': '', 'url': 'https://api.github.com/orgs/DataTalksClub', 'avatar_url': 'https://avatars.githubusercontent.com/u/72699292?'}}

Extracting and normlizing data by using the DLT method

In [6]:
import dlt

# defining the pipeline with the raw nested data
pipeline = dlt.pipeline(
    pipeline_name="github_data",
    destination="duckdb",
    dataset_name="events"    
)

# run the pipeline with raw nested data
info = pipeline.run(paginator_geteer(), table_name="events", write_disposition="replace")

# print the load summary
print(info)

# print all generated tables
print(pipeline.dataset().schema.data_table_names())

# print events table
pipeline.dataset().events.df()

2026-05-11 01:40:06,225|[WARNING]|17300|10084|dlt|validate.py|verify_normalized_table:113|In schema `github_data`: The following columns in table 'events' did not receive any data during this load and therefore could not have their types inferred:
  - payload__comment__performed_via_github_app
  - payload__comment__pin
  - payload__forkee__language
  - payload__forkee__license
  - payload__forkee__mirror_url
  - payload__issue__active_lock_reason
  - payload__issue__assignee
  - payload__issue__closed_at
  - payload__issue__milestone
  - payload__issue__performed_via_github_app
  - payload__issue__pinned_comment
  - payload__issue__state_reason
  - payload__issue__type

Unless type hints are provided, these columns will not be materialized in the destination.
One way to provide type hints is to use the 'columns' argument in the '@dlt.resource' decorator.  For example:

@dlt.resource(columns={'payload__comment__performed_via_github_app': {'data_type': 'text'}})

Pipeline github_data load step completed in 4.70 seconds
1 load package(s) were loaded to destination duckdb and into dataset events
The duckdb destination used duckdb:///c:\Users\vivek\PycharmProjects\pythonProject\Vivekcode\Data-Engineering and Data-Analysis\LLM models for a Data engineering\Data Engineering with python and AI or LLMs\github_data.duckdb location to store data
Load package 1778443803.3273678 is LOADED and contains no failed jobs
['events']

            id  ... payload__issue__user__site_admin
0   9288884998  ...                             <NA>
1   9288775541  ...                             <NA>
2   9287871995  ...                             <NA>
3   9287863593  ...                             <NA>
4   9287162371  ...                             <NA>
5   9286926968  ...                             <NA>
6   9286533726  ...                             <NA>
7   9285933558  ...                             <NA>
8   9285651299  ...                             <NA>
9   9285339812  ...                             <NA>
10  9284935714  ...                             <NA>
11  9284046327  ...                             <NA>
12  9283829320  ...                             <NA>
13  9283311258  ...                             <NA>
14  9282784025  ...                             <NA>
15  9282759437  ...                             <NA>
16  9282756793  ...                             <NA>
17  9282214441  ...                             <NA>
18  9281661238  ...                            False
19  9281646466  ...                             <NA>
20  9281588290  ...                             <NA>
21  9281127047  ...                             <NA>
22  9280262397  ...                             <NA>
23  9278136326  ...                             <NA>
24  9277714744  ...                             <NA>
25  9277667201  ...                             <NA>
26  9276845274  ...                             <NA>
27  9275435496  ...                             <NA>
28  9275431401  ...                             <NA>
29  9274990996  ...                             <NA>

[30 rows x 206 columns]

In [8]:
sql = """
SELECT * FROM events
"""

with pipeline.sql_client() as client:
    with client.execute_query(sql) as cursor:
        # get all data from the cursor as a list tuples
        print(cursor.fetchall())

[('9288884998', 'WatchEvent', True, datetime.datetime(2026, 5, 10, 20, 3, 28, tzinfo=<UTC>), 72699292, 'DataTalksClub', '', 'https://api.github.com/orgs/DataTalksClub', 'https://avatars.githubusercontent.com/u/72699292?', 'started', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 419661684, 'DataTalksClub/data-engineering-zoomcamp', 'https://api.github.com/repos/DataTalksClub/data-engineering-zoomcamp', 45904221, 'CRK1918', 'CRK1918', '', 'https://api.github.com/users/CRK1918', 'https://avatars.githubusercontent.com/u/45904221?', '1778443803.3273678', 'fxv1bMu5gA3UNA', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None), ('9288775541', 'ForkEvent', True, datetime.datetime(2026, 5, 10, 19, 54, 23, tzinfo=<UTC>), 72699292, 'DataTalksClub', '', 'https://api.github.com/orgs/DataTalksClub', 'https://avatars.githubusercontent.com/u/72699292?', 'forked', 1234911512, 'R_kgDOSZtBGA', 'DE-zoomcamp', 'lexiemeow/DE-zoomcamp', False, 'https://github.com/lexiemeow/DE-zoomcamp', 'Data Engineering Zoomcamp is a free 9-week course on building production-ready data pipelines. The next cohort starts in January 2026. Join the course here 👇🏼', True, 'https://api.github.com/repos/lexiemeow/DE-zoomcamp', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/forks', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/keys{/key_id}', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/collaborators{/collaborator}', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/teams', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/hooks', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/issues/events{/number}', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/events', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/assignees{/user}', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/branches{/branch}', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/tags', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/git/blobs{/sha}', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/git/tags{/sha}', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/git/refs{/sha}', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/git/trees{/sha}', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/statuses/{sha}', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/languages', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/stargazers', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/contributors', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/subscribers', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/subscription', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/commits{/sha}', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/git/commits{/sha}', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/comments{/number}', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/issues/comments{/number}', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/contents/{+path}', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/compare/{base}...{head}', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/merges', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/{archive_format}{/ref}', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/downloads', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/issues{/number}', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/pulls{/number}', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/milestones{/number}', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/notifications{?since,all,participating}', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/labels{/name}', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/releases{/id}', 'https://api.github.com/repos/lexiemeow/DE-zoomcamp/deployments', datetime.datetime(2026, 5, 10, 19, 54, 23, tzinfo=<UTC>), datetime.datetime(2026, 5, 10, 19, 54, 24, tzinfo=<UTC>), datetime.datetime(2026, 5, 3, 9, 21, 31, tzinfo=<UTC>), 'git://github.com/lexiemeow/DE-zoomcamp.git', 'git@github.com:lexiemeow/DE-zoomcamp.git', 'https://github.com/lexiemeow/DE-zoomcamp.git', 'https://github.com/lexiemeow/DE-zoomcamp', 'https://airtable.com/appzbS8Pkg9PL254a/shr6oVXeQvSI5HuWD', 10048, 0, 0, False, True, True, True, False, False, 0, False, False, 0, True, False, False, True, 'all', 'public', 0, 0, 0, 'main', 'lexiemeow', 39532049, 'MDQ6VXNlcjM5NTMyMDQ5', 'https://avatars.githubusercontent.com/u/39532049?v=4', '', 'https://api.github.com/users/lexiemeow', 'https://github.com/lexiemeow', 'https://api.github.com/users/lexiemeow/followers', 'https://api.github.com/users/lexiemeow/following{/other_user}', 'https://api.github.com/users/lexiemeow/gists{/gist_id}', 'https://api.github.com/users/lexiemeow/starred{/owner}{/repo}', 'https://api.github.com/users/lexiemeow/subscriptions', 'https://api.github.com/users/lexiemeow/orgs', 'https://api.github.com/users/lexiemeow/repos', 'https://api.github.com/users/lexiemeow/events{/privacy}', 'https://api.github.com/users/lexiemeow/received_events', 'User', 'public', False, 419661684, 'DataTalksClub/data-engineering-zoomcamp', 'https://api.github.com/repos/DataTalksClub/data-engineering-zoomcamp', 39532049, 'lexiemeow', 'lexiemeow', '', 'https://api.github.com/users/lexiemeow', 'https://avatars.githubusercontent.com/u/39532049?', '1778443803.3273678', 'm/DVqdOstGh3Fw', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None), ('9287871995', 'WatchEvent', True, datetime.datetime(2026, 5, 10, 18, 39, 31, tzinfo=<UTC>), 72699292, 'DataTalksClub', '', 'https://api.github.com/orgs/DataTalksClub', 'https://avatars.githubusercontent.com/u/72699292?', 'started', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 419661684, 'DataTalksClub/data-engineering-zoomcamp', 'https://api.github.com/repos/DataTalksClub/data-engineering-zoomcamp', 256124002, 'ederson-data', 'ederson-data', '', 'https://api.github.com/users/ederson-data', 'https://avatars.githubusercontent.com/u/256124002?', '1778443803.3273678', 'WcZ3xLfKe8xcTA', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None), ('9287863593', 'WatchEvent', True, datetime.datetime(2026, 5, 10, 18, 38, 51, tzinfo=<UTC>), 72699292, 'DataTalksClub', '', 'https://api.github.com/orgs/DataTalksClub', 'https://avatars.githubusercontent.com/u/72699292?', 'started', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 419661684, 'DataTalksClub/data-engineering-zoomcamp', 'https://api.github.com/repos/DataTalksClub/data-engineering-zoomcamp', 112778033, 'AbdalaOs', 'AbdalaOs', '', 'https://api.github.com/users/AbdalaOs', 'https://avatars.githubusercontent.com/u/112778033?', '1778443803.3273678', '1le/F3Rn0Y4/eQ', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None), ('9287162371', 'WatchEvent', True, datetime.datetime(2026, 5, 10, 17, 41, 25, tzinfo=<UTC>), 72699292, 'DataTalksClub', '', 'https://api.github.com/orgs/DataTalksClub', 'https://avatars.githubusercontent.com/u/72699292?', 'started', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 419661684, 'DataTalksClub/data-engineering-zoomcamp', 'https://api.github.com/repos/DataTalksClub/data-engineering-zoomcamp', 39532049, 'lexiemeow', 'lexiemeow', '', 'https://api.github.com/users/lexiemeow', 'https://avatars.githubusercontent.com/u/39532049?', '1778443803.3273678', 'rqggnZB5QVTsrA', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None), ('9286926968', 'ForkEvent', True, datetime.datetime(2026, 5, 10, 17, 21, 58, tzinfo=<UTC>), 72699292, 'DataTalksClub', '', 'https://api.github.com/orgs/DataTalksClub', 'https://avatars.githubusercontent.com/u/72699292?', 'forked', 1234818959, 'R_kgDOSZnXjw', 'data-engineering-zoomcamp', 'bmvsprasad/data-engineering-zoomcamp', False, 'https://github.com/bmvsprasad/data-engineering-zoomcamp', 'Data Engineering Zoomcamp is a free 9-week course on building production-ready data pipelines. The next cohort starts in January 2026. Join the course here 👇🏼', True, 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/forks', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/keys{/key_id}', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/collaborators{/collaborator}', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/teams', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/hooks', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/issues/events{/number}', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/events', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/assignees{/user}', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/branches{/branch}', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/tags', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/git/blobs{/sha}', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/git/tags{/sha}', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/git/refs{/sha}', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/git/trees{/sha}', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/statuses/{sha}', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/languages', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/stargazers', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/contributors', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/subscribers', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/subscription', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/commits{/sha}', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/git/commits{/sha}', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/comments{/number}', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/issues/comments{/number}', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/contents/{+path}', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/compare/{base}...{head}', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/merges', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/{archive_format}{/ref}', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/downloads', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/issues{/number}', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/pulls{/number}', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/milestones{/number}', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/notifications{?since,all,participating}', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/labels{/name}', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/releases{/id}', 'https://api.github.com/repos/bmvsprasad/data-engineering-zoomcamp/deployments', datetime.datetime(2026, 5, 10, 17, 21, 58, tzinfo=<UTC>), datetime.datetime(2026, 5, 10, 17, 21, 59, tzinfo=<UTC>), datetime.datetime(2026, 5, 3, 9, 21, 31, tzinfo=<UTC>), 'git://github.com/bmvsprasad/data-engineering-zoomcamp.git', 'git@github.com:bmvsprasad/data-engineering-zoomcamp.git', 'https://github.com/bmvsprasad/data-engineering-zoomcamp.git', 'https://github.com/bmvsprasad/data-engineering-zoomcamp', 'https://airtable.com/appzbS8Pkg9PL254a/shr6oVXeQvSI5HuWD', 10048, 0, 0, False, True, True, True, False, False, 0, False, False, 0, True, False, False, True, 'all', 'public', 0, 0, 0, 'main', 'bmvsprasad', 13960455, 'MDQ6VXNlcjEzOTYwNDU1', 'https://avatars.githubusercontent.com/u/13960455?v=4', '', 'https://api.github.com/users/bmvsprasad', 'https://github.com/bmvsprasad', 'https://api.github.com/users/bmvsprasad/followers', 'https://api.github.com/users/bmvsprasad/following{/other_user}', 'https://api.github.com/users/bmvsprasad/gists{/gist_id}', 'https://api.github.com/users/bmvsprasad/starred{/owner}{/repo}', 'https://api.github.com/users/bmvsprasad/subscriptions', 'https://api.github.com/users/bmvsprasad/orgs', 'https://api.github.com/users/bmvsprasad/repos', 'https://api.github.com/users/bmvsprasad/events{/privacy}', 'https://api.github.com/users/bmvsprasad/received_events', 'User', 'public', False, 419661684, 'DataTalksClub/data-engineering-zoomcamp', 'https://api.github.com/repos/DataTalksClub/data-engineering-zoomcamp', 13960455, 'bmvsprasad', 'bmvsprasad', '', 'https://api.github.com/users/bmvsprasad', 'https://avatars.githubusercontent.com/u/13960455?', '1778443803.3273678', 'qDsn0Qw67XKr9Q', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None), ('9286533726', 'WatchEvent', True, datetime.datetime(2026, 5, 10, 16, 49, 40, tzinfo=<UTC>), 72699292, 'DataTalksClub', '', 'https://api.github.com/orgs/DataTalksClub', 'https://avatars.githubusercontent.com/u/72699292?', 'started', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 419661684, 'DataTalksClub/data-engineering-zoomcamp', 'https://api.github.com/repos/DataTalksClub/data-engineering-zoomcamp', 281697474, 'malkiwalid', 'malkiwalid', '', 'https://api.github.com/users/malkiwalid', 'https://avatars.githubusercontent.com/u/281697474?', '1778443803.3273678', '+R6wgt8h9YDiPQ', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None), ('9285933558', 'WatchEvent', True, datetime.datetime(2026, 5, 10, 16, 2, 51, tzinfo=<UTC>), 72699292, 'DataTalksClub', '', 'https://api.github.com/orgs/DataTalksClub', 'https://avatars.githubusercontent.com/u/72699292?', 'started', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 

In [ ]:
# print the default schema in a pretty YML file
print(pipeline.default_schema.to_pretty_yaml())
# print(pipeline.default_schema.to_pretty_json())

version: 3
version_hash: AW6Yxi1TzxrD8KoX0y5SaI8ySrArZKA6WUWgaBCUXi8=
engine_version: 11
name: github_data
tables:
  _dlt_version:
    columns:
      version:
        data_type: bigint
        nullable: false
      engine_version:
        data_type: bigint
        nullable: false
      inserted_at:
        data_type: timestamp
        nullable: false
      schema_name:
        data_type: text
        nullable: false
      version_hash:
        data_type: text
        nullable: false
      schema:
        data_type: text
        nullable: false
    write_disposition: skip
    resource: _dlt_version
    description: Created by DLT. Tracks schema updates
  _dlt_loads:
    columns:
      load_id:
        data_type: text
        nullable: false
        precision: 64
      schema_name:
        data_type: text
        nullable: true
      status:
        data_type: bigint
        nullable: false
      inserted_at:
        data_type: timestamp
        nullable: false
      schema_version_hash:
        data_type: text
        nullable: true
    write_disposition: skip
    resource: _dlt_loads
    description: Created by DLT. Tracks completed loads
  events:
    columns:
      id:
        data_type: text
        nullable: true
      type:
        data_type: text
        nullable: true
      public:
        data_type: bool
        nullable: true
      created_at:
        data_type: timestamp
        nullable: true
      org__id:
        data_type: bigint
        nullable: true
      org__login:
        data_type: text
        nullable: true
      org__gravatar_id:
        data_type: text
        nullable: true
      org__url:
        data_type: text
        nullable: true
      org__avatar_url:
        data_type: text
        nullable: true
      payload__action:
        data_type: text
        nullable: true
      payload__forkee__id:
        data_type: bigint
        nullable: true
      payload__forkee__node_id:
        data_type: text
        nullable: true
      payload__forkee__name:
        data_type: text
        nullable: true
      payload__forkee__full_name:
        data_type: text
        nullable: true
      payload__forkee__private:
        data_type: bool
        nullable: true
      payload__forkee__html_url:
        data_type: text
        nullable: true
      payload__forkee__description:
        data_type: text
        nullable: true
      payload__forkee__fork:
        data_type: bool
        nullable: true
      payload__forkee__url:
        data_type: text
        nullable: true
      payload__forkee__forks_url:
        data_type: text
        nullable: true
      payload__forkee__keys_url:
        data_type: text
        nullable: true
      payload__forkee__collaborators_url:
        data_type: text
        nullable: true
      payload__forkee__teams_url:
        data_type: text
        nullable: true
      payload__forkee__hooks_url:
        data_type: text
        nullable: true
      payload__forkee__issue_events_url:
        data_type: text
        nullable: true
      payload__forkee__events_url:
        data_type: text
        nullable: true
      payload__forkee__assignees_url:
        data_type: text
        nullable: true
      payload__forkee__branches_url:
        data_type: text
        nullable: true
      payload__forkee__tags_url:
        data_type: text
        nullable: true
      payload__forkee__blobs_url:
        data_type: text
        nullable: true
      payload__forkee__git_tags_url:
        data_type: text
        nullable: true
      payload__forkee__git_refs_url:
        data_type: text
        nullable: true
      payload__forkee__trees_url:
        data_type: text
        nullable: true
      payload__forkee__statuses_url:
        data_type: text
        nullable: true
      payload__forkee__languages_url:
        data_type: text
        nullable: true
      payload__forkee__stargazers_url:
        data_type: text
        nullable: true
      payload__forkee__contributors_url:
        data_type: text
        nullable: true
      payload__forkee__subscribers_url:
        data_type: text
        nullable: true
      payload__forkee__subscription_url:
        data_type: text
        nullable: true
      payload__forkee__commits_url:
        data_type: text
        nullable: true
      payload__forkee__git_commits_url:
        data_type: text
        nullable: true
      payload__forkee__comments_url:
        data_type: text
        nullable: true
      payload__forkee__issue_comment_url:
        data_type: text
        nullable: true
      payload__forkee__contents_url:
        data_type: text
        nullable: true
      payload__forkee__compare_url:
        data_type: text
        nullable: true
      payload__forkee__merges_url:
        data_type: text
        nullable: true
      payload__forkee__archive_url:
        data_type: text
        nullable: true
      payload__forkee__downloads_url:
        data_type: text
        nullable: true
      payload__forkee__issues_url:
        data_type: text
        nullable: true
      payload__forkee__pulls_url:
        data_type: text
        nullable: true
      payload__forkee__milestones_url:
        data_type: text
        nullable: true
      payload__forkee__notifications_url:
        data_type: text
        nullable: true
      payload__forkee__labels_url:
        data_type: text
        nullable: true
      payload__forkee__releases_url:
        data_type: text
        nullable: true
      payload__forkee__deployments_url:
        data_type: text
        nullable: true
      payload__forkee__created_at:
        data_type: timestamp
        nullable: true
      payload__forkee__updated_at:
        data_type: timestamp
        nullable: true
      payload__forkee__pushed_at:
        data_type: timestamp
        nullable: true
      payload__forkee__git_url:
        data_type: text
        nullable: true
      payload__forkee__ssh_url:
        data_type: text
        nullable: true
      payload__forkee__clone_url:
        data_type: text
        nullable: true
      payload__forkee__svn_url:
        data_type: text
        nullable: true
      payload__forkee__homepage:
        data_type: text
        nullable: true
      payload__forkee__size:
        data_type: bigint
        nullable: true
      payload__forkee__stargazers_count:
        data_type: bigint
        nullable: true
      payload__forkee__watchers_count:
        data_type: bigint
        nullable: true
      payload__forkee__has_issues:
        data_type: bool
        nullable: true
      payload__forkee__has_projects:
        data_type: bool
        nullable: true
      payload__forkee__has_downloads:
        data_type: bool
        nullable: true
      payload__forkee__has_wiki:
        data_type: bool
        nullable: true
      payload__forkee__has_pages:
        data_type: bool
        nullable: true
      payload__forkee__has_discussions:
        data_type: bool
        nullable: true
      payload__forkee__forks_count:
        data_type: bigint
        nullable: true
      payload__forkee__archived:
        data_type: bool
        nullable: true
      payload__forkee__disabled:
        data_type: bool
        nullable: true
      payload__forkee__open_issues_count:
        data_type: bigint
        nullable: true
      payload__forkee__allow_forking:
        data_type: bool
        nullable: true
      payload__forkee__is_template:
        data_type: bool
        nullable: true
      payload__forkee__web_commit_signoff_required:
        data_type: bool
        nullable: true
      payload__forkee__has_pull_requests:
        data_type: bool
        nullable: true
      payload__forkee__pull_request_creation_policy:
        data_type: text
        nullable: true
      payload__forkee__visibility:
        data_type: text
        nullable: true
      payload__forkee__forks:
        data_type: bigint
        nullable: true
      payload__forkee__open_issues:
        data_type: bigint
        nullable: true
      payload__forkee__watchers:
        data_type: bigint
        nullable: true
      payload__forkee__default_branch:
        data_type: text
        nullable: true
      payload__forkee__owner__login:
        data_type: text
        nullable: true
      payload__forkee__owner__id:
        data_type: bigint
        nullable: true
      payload__forkee__owner__node_id:
        data_type: text
        nullable: true
      payload__forkee__owner__avatar_url:
        data_type: text
        nullable: true
      payload__forkee__owner__gravatar_id:
        data_type: text
        nullable: true
      payload__forkee__owner__url:
        data_type: text
        nullable: true
      payload__forkee__owner__html_url:
        data_type: text
        nullable: true
      payload__forkee__owner__followers_url:
        data_type: text
        nullable: true
      payload__forkee__owner__following_url:
        data_type: text
        nullable: true
      payload__forkee__owner__gists_url:
        data_type: text
        nullable: true
      payload__forkee__owner__starred_url:
        data_type: text
        nullable: true
      payload__forkee__owner__subscriptions_url:
        data_type: text
        nullable: true
      payload__forkee__owner__organizations_url:
        data_type: text
        nullable: true
      payload__forkee__owner__repos_url:
        data_type: text
        nullable: true
      payload__forkee__owner__events_url:
        data_type: text
        nullable: true
      payload__forkee__owner__received_events_url:
        data_type: text
        nullable: true
      payload__forkee__owner__type:
        data_type: text
        nullable: true
      payload__forkee__owner__user_view_type:
        data_type: text
        nullable: true
      payload__forkee__owner__site_admin:
        data_type: bool
        nullable: true
      repo__id:
        data_type: bigint
        nullable: true
      repo__name:
        data_type: text
        nullable: true
      repo__url:
        data_type: text
        nullable: true
      actor__id:
        data_type: bigint
        nullable: true
      actor__login:
        data_type: text
        nullable: true
      actor__display_login:
        data_type: text
        nullable: true
      actor__gravatar_id:
        data_type: text
        nullable: true
      actor__url:
        data_type: text
        nullable: true
      actor__avatar_url:
        data_type: text
        nullable: true
      _dlt_load_id:
        data_type: text
        nullable: false
      _dlt_id:
        data_type: text
        nullable: false
        unique: true
        row_key: true
      payload__comment__url:
        data_type: text
        nullable: true
      payload__comment__html_url:
        data_type: text
        nullable: true
      payload__comment__issue_url:
        data_type: text
        nullable: true
      payload__comment__id:
        data_type: bigint
        nullable: true
      payload__comment__node_id:
        data_type: text
        nullable: true
      payload__comment__created_at:
        data_type: timestamp
        nullable: true
      payload__comment__updated_at:
        data_type: timestamp
        nullable: true
      payload__comment__body:
        data_type: text
        nullable: true
      payload__comment__reactions__url:
        data_type: text
        nullable: true
      payload__comment__reactions__total_count:
        data_type: bigint
        nullable: true
      payload__comment__reactions__x1:
        data_type: bigint
        nullable: true
      payload__comment__reactions___1:
        data_type: bigint
        nullable: true
      payload__comment__reactions__laugh:
        data_type: bigint
        nullable: true
      payload__comment__reactions__hooray:
        data_type: bigint
        nullable: true
      payload__comment__reactions__confused:
        data_type: bigint
        nullable: true
      payload__comment__reactions__heart:
        data_type: bigint
        nullable: true
      payload__comment__reactions__rocket:
        data_type: bigint
        nullable: true
      payload__comment__reactions__eyes:
        data_type: bigint
        nullable: true
      payload__comment__user__login:
        data_type: text
        nullable: true
      payload__comment__user__id:
        data_type: bigint
        nullable: true
      payload__comment__user__node_id:
        data_type: text
        nullable: true
      payload__comment__user__avatar_url:
        data_type: text
        nullable: true
      payload__comment__user__gravatar_id:
        data_type: text
        nullable: true
      payload__comment__user__url:
        data_type: text
        nullable: true
      payload__comment__user__html_url:
        data_type: text
        nullable: true
      payload__comment__user__followers_url:
        data_type: text
        nullable: true
      payload__comment__user__following_url:
        data_type: text
        nullable: true
      payload__comment__user__gists_url:
        data_type: text
        nullable: true
      payload__comment__user__starred_url:
        data_type: text
        nullable: true
      payload__comment__user__subscriptions_url:
        data_type: text
        nullable: true
      payload__comment__user__organizations_url:
        data_type: text
        nullable: true
      payload__comment__user__repos_url:
        data_type: text
        nullable: true
      payload__comment__user__events_url:
        data_type: text
        nullable: true
      payload__comment__user__received_events_url:
        data_type: text
        nullable: true
      payload__comment__user__type:
        data_type: text
        nullable: true
      payload__comment__user__user_view_type:
        data_type: text
        nullable: true
      payload__comment__user__site_admin:
        data_type: bool
        nullable: true
      payload__issue__url:
        data_type: text
        nullable: true
      payload__issue__repository_url:
        data_type: text
        nullable: true
      payload__issue__labels_url:
        data_type: text
        nullable: true
      payload__issue__comments_url:
        data_type: text
        nullable: true
      payload__issue__events_url:
        data_type: text
        nullable: true
      payload__issue__html_url:
        data_type: text
        nullable: true
      payload__issue__id:
        data_type: bigint
        nullable: true
      payload__issue__node_id:
        data_type: text
        nullable: true
      payload__issue__number:
        data_type: bigint
        nullable: true
      payload__issue__title:
        data_type: text
        nullable: true
      payload__issue__state:
        data_type: text
        nullable: true
      payload__issue__locked:
        data_type: bool
        nullable: true
      payload__issue__comments:
        data_type: bigint
        nullable: true
      payload__issue__created_at:
        data_type: timestamp
        nullable: true
      payload__issue__updated_at:
        data_type: timestamp
        nullable: true
      payload__issue__body:
        data_type: text
        nullable: true
      payload__issue__timeline_url:
        data_type: text
        nullable: true
      payload__issue__reactions__url:
        data_type: text
        nullable: true
      payload__issue__reactions__total_count:
        data_type: bigint
        nullable: true
      payload__issue__reactions__x1:
        data_type: bigint
        nullable: true
      payload__issue__reactions___1:
        data_type: bigint
        nullable: true
      payload__issue__reactions__laugh:
        data_type: bigint
        nullable: true
      payload__issue__reactions__hooray:
        data_type: bigint
        nullable: true
      payload__issue__reactions__confused:
        data_type: bigint
        nullable: true
      payload__issue__reactions__heart:
        data_type: bigint
        nullable: true
      payload__issue__reactions__rocket:
        data_type: bigint
        nullable: true
      payload__issue__reactions__eyes:
        data_type: bigint
        nullable: true
      payload__issue__issue_dependencies_summary__blocked_by:
        data_type: bigint
        nullable: true
      payload__issue__issue_dependencies_summary__total_blocked_by:
        data_type: bigint
        nullable: true
      payload__issue__issue_dependencies_summary__blocking:
        data_type: bigint
        nullable: true
      payload__issue__issue_dependencies_summary__total_blocking:
        data_type: bigint
        nullable: true
      payload__issue__sub_issues_summary__total:
        data_type: bigint
        nullable: true
      payload__issue__sub_issues_summary__completed:
        data_type: bigint
        nullable: true
      payload__issue__sub_issues_summary__percent_completed:
        data_type: bigint
        nullable: true
      payload__issue__user__login:
        data_type: text
        nullable: true
      payload__issue__user__id:
        data_type: bigint
        nullable: true
      payload__issue__user__node_id:
        data_type: text
        nullable: true
      payload__issue__user__avatar_url:
        data_type: text
        nullable: true
      payload__issue__user__gravatar_id:
        data_type: text
        nullable: true
      payload__issue__user__url:
        data_type: text
        nullable: true
      payload__issue__user__html_url:
        data_type: text
        nullable: true
      payload__issue__user__followers_url:
        data_type: text
        nullable: true
      payload__issue__user__following_url:
        data_type: text
        nullable: true
      payload__issue__user__gists_url:
        data_type: text
        nullable: true
      payload__issue__user__starred_url:
        data_type: text
        nullable: true
      payload__issue__user__subscriptions_url:
        data_type: text
        nullable: true
      payload__issue__user__organizations_url:
        data_type: text
        nullable: true
      payload__issue__user__repos_url:
        data_type: text
        nullable: true
      payload__issue__user__events_url:
        data_type: text
        nullable: true
      payload__issue__user__received_events_url:
        data_type: text
        nullable: true
      payload__issue__user__type:
        data_type: text
        nullable: true
      payload__issue__user__user_view_type:
        data_type: text
        nullable: true
      payload__issue__user__site_admin:
        data_type: bool
        nullable: true
    write_disposition: replace
    resource: events
    x-normalizer:
      seen-data: true
  _dlt_pipeline_state:
    columns:
      version:
        data_type: bigint
        nullable: false
      engine_version:
        data_type: bigint
        nullable: false
      pipeline_name:
        data_type: text
        nullable: false
      state:
        data_type: text
        nullable: false
      created_at:
        data_type: timestamp
        nullable: false
      version_hash:
        data_type: text
        nullable: true
      _dlt_load_id:
        data_type: text
        nullable: false
        precision: 64
      _dlt_id:
        data_type: text
        nullable: false
        unique: true
        row_key: true
    write_disposition: append
    file_format: preferred
    resource: _dlt_pipeline_state
    x-normalizer:
      seen-data: true
settings:
  detections:
  - iso_timestamp
  default_hints:
    not_null:
    - _dlt_id
    - _dlt_root_id
    - _dlt_parent_id
    - _dlt_list_idx
    - _dlt_load_id
    parent_key:
    - _dlt_parent_id
    root_key:
    - _dlt_root_id
    unique:
    - _dlt_id
    row_key:
    - _dlt_id
normalizers:
  names: snake_case
  json:
    module: dlt.common.normalizers.json.relational
previous_hashes:
- fdjbFz2mH1GfZz6sTk0PYJvDZEz1b1nGcWmiwwtbq1E=
- S21hH7Fw0geoC5kiIOEf2xs9l+NNSc+wc89eYA92Dk4=
- YwobM+gk/SvtKe0mNXU10nh+h2G3n09AuT6miBScMCM=

Setting a Data contracts

1) Load data and set a contract
2) Add column to the incoming data set (append in py) and see it get rejected
3) Remove the contract and see it get accepted

In [ ]:
# example data contract
from dlt.sources.helpers.rest_client import RESTClient
from dlt.sources.helpers.rest_client.auth import BearerTokenAuth
from dlt.sources.helpers.rest_client.paginators import JSONLinkPaginator
# This library added
import dlt

BASE_URL = "https://api.github.com/repos/DataTalksClub/data-engineering-zoomcamp"
API_TOKEN = "Your Token"
MAX_PAGES_TO_READ = 10

# The below line, it will add the table but adding the column in table or change the data_type is not allowed because it is freeze
# @dlt.resource(name="events", schema_contract={"tables": "evolve", "columns": "freeze", "data_type": "freeze"})

# The below line, it will allow the change in all three things
@dlt.resource(name="events", schema_contract={"tables": "evolve", "columns": "evolve", "data_type": "evolve"})
def paginator_geteer():
    client = RESTClient(
        base_url=BASE_URL,
        # auth=BearerTokenAuth(token=API_TOKEN), if you use token then use this line
        paginator = JSONLinkPaginator(next_url_path="next")    
    )

    for page_number, page in enumerate(client.paginate("/events"), start=1):
        if page_number > MAX_PAGES_TO_READ:
            break
        for record in page:
            # we wanna try to add some data that does not condrom
            record['extra_data'] = "abc" # abc shows the string value data_type
            yield record

# defining the pipeline with the raw nested data
pipeline = dlt.pipeline(
    pipeline_name="github_data",
    destination="duckdb",
    dataset_name="events"    
)

# run the pipeline with raw nested data
info = pipeline.run(paginator_geteer(), table_name="events", write_disposition="replace")

# print the load summary
print(info)

# print all generated tables
print(pipeline.dataset().schema.data_table_names())

# print events table
pipeline.dataset().events.df()

Alerting the schema changes

Loading data with DLT

In [ ]:
from dlt.sources.helpers.rest_client import RESTClient
from dlt.sources.helpers.rest_client.auth import BearerTokenAuth
from dlt.sources.helpers.rest_client.paginators import JSONLinkPaginator
# This library added
import dlt
import os

os.environ["ACCESS_TOKEN"] = "Your Token"
BASE_URL = "https://api.github.com/repos/DataTalksClub/data-engineering-zoomcamp"
MAX_PAGES_TO_READ = 10

@dlt.resource(name="events", write_disposition="replace") # write_disposition="replace" added here
# def paginator_geteer(access_token=dlt.secrets.value):
def paginator_geteer():
    client = RESTClient(
        base_url=BASE_URL,
        # auth=BearerTokenAuth(token=access_token), if you use token then use this line
        paginator = JSONLinkPaginator(next_url_path="next")    
    )

    for page_number, page in enumerate(client.paginate("/events"), start=1):
        if page_number > MAX_PAGES_TO_READ:
            break
        for record in page:
            yield record

# defining the pipeline with the raw nested data
pipeline = dlt.pipeline(
    pipeline_name="github_data",
    destination="duckdb",
    dataset_name="events"    
)

# run the pipeline with raw nested data
load_info = pipeline.run(paginator_geteer)

# print the load trace summary
print(pipeline.last_trace)

# print events table
pipeline.dataset().events.df()

Incremental loading

In [ ]:
from dlt.sources.helpers.rest_client import RESTClient
from dlt.sources.helpers.rest_client.auth import BearerTokenAuth
from dlt.sources.helpers.rest_client.paginators import JSONLinkPaginator
# This library added
import dlt
import os

os.environ["ACCESS_TOKEN"] = "Your Token"
BASE_URL = "https://api.github.com/repos/DataTalksClub/data-engineering-zoomcamp"
MAX_PAGES_TO_READ = 10

@dlt.resource(name="events", write_disposition="append") # write_disposition="append" means we will load data in table
# def paginator_geteer(access_token=dlt.secrets.value):
def paginator_geteer(access_token=dlt.secrets.value, 
                     cursor_date=dlt.sources.incremental(
                         "create_at",  # field to track, our timestamp
                         initial_value="03.10.2025" # set default for first run
                     )
                     ):
    client = RESTClient(
        base_url=BASE_URL,
        # auth=BearerTokenAuth(token=access_token), if you use token then use this line
        paginator = JSONLinkPaginator(next_url_path="next")    
    )

    for page_number, page in enumerate(client.paginate("/events"), start=1):
        if page_number > MAX_PAGES_TO_READ:
            break
        for record in page:
            yield record

# defining the pipeline with the raw nested data
pipeline = dlt.pipeline(
    pipeline_name="github_data",
    destination="duckdb",
    dataset_name="events"    
)

# run the pipeline with raw nested data
load_info = pipeline.run(paginator_geteer)

# print the load trace summary
print(pipeline.last_trace)

# print events table
pipeline.dataset().events.df()

SQL (DuckDB) to SQL (Postgrey SQL) copy data

In [ ]:
import dlt
from dlt.sources.sql_database import sql_database

# ------------------------------------------------
# SOURCE = DUCKDB
# ------------------------------------------------

source = sql_database(
    credentials="duckdb:///github_data.duckdb",
    table_names=["events"],
    backend="pyarrow"
)

# ------------------------------------------------
# DESTINATION = POSTGRES
# ------------------------------------------------

pipeline = dlt.pipeline(
    pipeline_name="duckdb_to_postgres",
    destination="postgres",
    dataset_name="public"
)

# ------------------------------------------------
# RUN PIPELINE
# ------------------------------------------------

load_info = pipeline.run(
    source,
    credentials="postgresql://postgres:password@localhost:5432/mydatabase"
)

print(load_info)

In [ ]:
import dlt
from dlt.sources.sql_database import sql_database

# ------------------------------------------------
# SOURCE = DUCKDB
# ------------------------------------------------

source = sql_database(
    credentials="duckdb:///github_data.duckdb",
    table_names=["events"],
    backend="pyarrow"
)

# ------------------------------------------------
# DESTINATION = SQLITE
# ------------------------------------------------

pipeline = dlt.pipeline(
    pipeline_name="duckdb_to_sqlite",
    destination="filesystem",  # temporary
    dataset_name="sqlite_data"
)

# ------------------------------------------------
# LOAD SOURCE DATA INTO PYTHON
# ------------------------------------------------

data = list(source.resources["events"])

# ------------------------------------------------
# WRITE TO SQLITE MANUALLY
# ------------------------------------------------

import sqlite3
import pandas as pd

conn = sqlite3.connect("events.sqlite")

df = pd.DataFrame(data)

df.to_sql(
    "events",
    conn,
    if_exists="replace",
    index=False
)

print("Transferred DuckDB -> SQLite successfully")

Back Filling

Slowly changing dimension SCD2

we use this when data is multiple times then we will check first and last when it is fast changing
so we use this when we have slow change in database, something like customer data change per day, not every day

In [11]:
data = [
    {"name": "Vincent Crabbe", "designation": "student", "date_started": "1991-09-01T09:00:00Z"}, 
    {"name":"Gregory Goyle", "designation": "student", "date_started": "1991-09-01T09:00:00Z"}, 
    {"name": "Draco Malfoy", "designation": "student", "date_started": "1991-09-01T09:00:00Z"}]
data_updated = [
    {"name": "Vincent Crabbe", "designation": "student", "date_started": "1991-09-01T09:00:00Z"}, 
    {"name": "Gregory Goyle", "designation": "student", "date_started": "1991-09-01T09:00:00Z"}, 
    {"name": "Draco Malfoy", "designation": "expelled", "date_started": "1991-09-01T09:00:00Z"}]

In [14]:
import dlt
pipeline = dlt.pipeline(
pipeline_name="hogwarts_pipeline",
destination="duckdb",
dataset_name="hogwarts",)

load_info= pipeline.run(
    data_updated,
    table_name="creatures",
    write_disposition={
        "disposition": "merge", # <- specifies that existing data should be merged rather than replaced 
        "strategy": "scd2"# <- enables SCD2 tracking, which keeps historical records of changes
    }
)
print(load_info)

# print creatures table
pipeline.dataset().creatures.df()

Pipeline hogwarts_pipeline load step completed in 2.16 seconds
1 load package(s) were loaded to destination duckdb and into dataset hogwarts
The duckdb destination used duckdb:///c:\Users\vivek\PycharmProjects\pythonProject\Vivekcode\Data-Engineering and Data-Analysis\LLM models for a Data engineering\Data Engineering with python and AI or LLMs\hogwarts_pipeline.duckdb location to store data
Load package 1778448440.5966768 is LOADED and contains no failed jobs

                   _dlt_valid_from  ...         _dlt_id
0 2026-05-10 21:11:34.922165+00:00  ...  P94fUt8jUkzx6A
1 2026-05-10 21:11:34.922165+00:00  ...  Wv4kISjkizZwkQ
2 2026-05-10 21:11:34.922165+00:00  ...  r7u0vNojh+gvEQ
3 2026-05-10 21:27:20.596677+00:00  ...  KCWs+o6jOW/aLQ

[4 rows x 7 columns]

In [13]:
load_info= pipeline.run(
    data,
    table_name="creatures",
    write_disposition={
        "disposition": "merge", # <- specifies that existing data should be merged rather than replaced 
        "strategy": "scd2"# <- enables SCD2 tracking, which keeps historical records of changes
    }
)
print(load_info)

# print creatures table
pipeline.dataset().creatures.df()

Pipeline hogwarts_pipeline load step completed in 1.19 seconds
1 load package(s) were loaded to destination duckdb and into dataset hogwarts
The duckdb destination used duckdb:///c:\Users\vivek\PycharmProjects\pythonProject\Vivekcode\Data-Engineering and Data-Analysis\LLM models for a Data engineering\Data Engineering with python and AI or LLMs\hogwarts_pipeline.duckdb location to store data
Load package 1778447523.6475031 is LOADED and contains no failed jobs

                   _dlt_valid_from  ...         _dlt_id
0 2026-05-10 21:11:34.922165+00:00  ...  P94fUt8jUkzx6A
1 2026-05-10 21:11:34.922165+00:00  ...  Wv4kISjkizZwkQ
2 2026-05-10 21:11:34.922165+00:00  ...  r7u0vNojh+gvEQ

[3 rows x 7 columns]

Loading to Data lakes: are for storage, like a S3 
Lakehouse and catalogs

In [8]:
from dlt.sources.helpers.rest_client import RESTClient
from dlt.sources.helpers.rest_client.auth import BearerTokenAuth
from dlt.sources.helpers.rest_client.paginators import JSONLinkPaginator
# This library added
import dlt
import os

os.environ["ACCESS_TOKEN"] = "Your Token"
BASE_URL = "https://api.github.com/repos/DataTalksClub/data-engineering-zoomcamp"
MAX_PAGES_TO_READ = 10

@dlt.resource(name="events", write_disposition="replace") # write_disposition="replace" added here
# def paginator_getter(access_token=dlt.secrets.value):
def paginator_getter():
    client = RESTClient(
        base_url=BASE_URL,
        # auth=BearerTokenAuth(token=access_token), if you use token then use this line
        paginator = JSONLinkPaginator(next_url_path="next")    
    )

    for page_number, page in enumerate(client.paginate("/events"), start=1):
        if page_number > MAX_PAGES_TO_READ:
            break
        for record in page:
            yield record
            
os.environ["BUCKET_URL"] = "./content"

pipeline = dlt.pipeline(
pipeline_name="fs_pipeline_v2",
destination="filesystem",
dataset_name="fs_data",)

load_info = pipeline.run(
paginator_getter,
loader_file_format="parquet", # choose a file format, csv, json or parquet
write_disposition="append",) # file destination doesn't support merge and will fall back to 'append'

print(pipeline.last_trace)

2026-05-12 21:21:58,324|[WARNING]|14656|13100|dlt|validate.py|verify_normalized_table:113|In schema `fs_pipeline_v2`: The following columns in table 'events' did not receive any data during this load and therefore could not have their types inferred:
  - payload__forkee__language
  - payload__forkee__license
  - payload__forkee__mirror_url

Unless type hints are provided, these columns will not be materialized in the destination.
One way to provide type hints is to use the 'columns' argument in the '@dlt.resource' decorator.  For example:

@dlt.resource(columns={'payload__forkee__language': {'data_type': 'text'}})

Run started at 2026-05-12 15:51:52.537282+00:00 and COMPLETED in 6.58 seconds with 4 steps.
Step extract COMPLETED in 2.42 seconds.

Load package 1778601112.866457 is EXTRACTED and NOT YET LOADED to the destination and contains no failed jobs

Step normalize COMPLETED in 3.20 seconds.
Normalized data for the following tables:
- events: 30 row(s)
- _dlt_pipeline_state: 1 row(s)

Load package 1778601112.866457 is NORMALIZED and NOT YET LOADED to the destination and contains no failed jobs

Step load COMPLETED in 0.70 seconds.
Pipeline fs_pipeline_v2 load step completed in 0.62 seconds
1 load package(s) were loaded to destination filesystem and into dataset fs_data
The filesystem destination used file:///C:/Users/vivek/PycharmProjects/pythonProject/Vivekcode/Data-Engineering%20and%20Data-Analysis/LLM%20models%20for%20a%20Data%20engineering/Data%20Engineering%20with%20python%20and%20AI%20or%20LLMs/content location to store data
Load package 1778601112.866457 is LOADED and contains no failed jobs

Step run COMPLETED in 6.58 seconds.
Pipeline fs_pipeline_v2 load step completed in 0.62 seconds
1 load package(s) were loaded to destination filesystem and into dataset fs_data
The filesystem destination used file:///C:/Users/vivek/PycharmProjects/pythonProject/Vivekcode/Data-Engineering%20and%20Data-Analysis/LLM%20models%20for%20a%20Data%20engineering/Data%20Engineering%20with%20python%20and%20AI%20or%20LLMs/content location to store data
Load package 1778601112.866457 is LOADED and contains no failed jobs

In [9]:
# explore loaded data
pipeline.dataset().events.df()

,id,type,public,created_at,org__id,org__login,org__gravatar_id,org__url,org__avatar_url,payload__action,...,payload__forkee__owner__gists_url,payload__forkee__owner__starred_url,payload__forkee__owner__subscriptions_url,payload__forkee__owner__organizations_url,payload__forkee__owner__repos_url,payload__forkee__owner__events_url,payload__forkee__owner__received_events_url,payload__forkee__owner__type,payload__forkee__owner__user_view_type,payload__forkee__owner__site_admin
0,9369418478,WatchEvent,True,2026-05-12 15:07:43+00:00,72699292,DataTalksClub,,https://api.github.com/orgs/DataTalksClub,https://avatars.githubusercontent.com/u/72699292?,started,...,None,None,None,None,None,None,None,None,None,<NA>
1,9368837846,WatchEvent,True,2026-05-12 14:55:13+00:00,72699292,DataTalksClub,,https://api.github.com/orgs/DataTalksClub,https://avatars.githubusercontent.com/u/72699292?,started,...,None,None,None,None,None,None,None,None,None,<NA>
2,9365203071,WatchEvent,True,2026-05-12 13:34:13+00:00,72699292,DataTalksClub,,https://api.github.com/orgs/DataTalksClub,https://avatars.githubusercontent.com/u/72699292?,started,...,None,None,None,None,None,None,None,None,None,<NA>
3,9364953667,WatchEvent,True,2026-05-12 13:28:23+00:00,72699292,DataTalksClub,,https://api.github.com/orgs/DataTalksClub,https://avatars.githubusercontent.com/u/72699292?,started,...,None,None,None,None,None,None,None,None,None,<NA>
4,9360787707,WatchEvent,True,2026-05-12 11:47:04+00:00,72699292,DataTalksClub,,https://api.github.com/orgs/DataTalksClub,https://avatars.githubusercontent.com/u/72699292?,started,...,None,None,None,None,None,None,None,None,None,<NA>
5,9359893980,WatchEvent,True,2026-05-12 11:23:26+00:00,72699292,DataTalksClub,,https://api.github.com/orgs/DataTalksClub,https://avatars.githubusercontent.com/u/72699292?,started,...,None,None,None,None,None,None,None,None,None,<NA>
6,9359740551,WatchEvent,True,2026-05-12 11:19:28+00:00,72699292,DataTalksClub,,https://api.github.com/orgs/DataTalksClub,https://avatars.githubusercontent.com/u/72699292?,started,...,None,None,None,None,None,None,None,None,None,<NA>
7,9358136475,WatchEvent,True,2026-05-12 10:37:12+00:00,72699292,DataTalksClub,,https://api.github.com/orgs/DataTalksClub,https://avatars.githubusercontent.com/u/72699292?,started,...,None,None,None,None,None,None,None,None,None,<NA>
8,9354065319,WatchEvent,True,2026-05-12 08:54:33+00:00,72699292,DataTalksClub,,https://api.github.com/orgs/DataTalksClub,https://avatars.githubusercontent.com/u/72699292?,started,...,None,None,None,None,None,None,None,None,None,<NA>
9,9354042581,WatchEvent,True,2026-05-12 08:54:00+00:00,72699292,DataTalksClub,,https://api.github.com/orgs/DataTalksClub,https://avatars.githubusercontent.com/u/72699292?,started,...,None,None,None,None,None,None,None,None,None,<NA>
10,9351066502,WatchEvent,True,2026-05-12 07:38:00+00:00,72699292,DataTalksClub,,https://api.github.com/orgs/DataTalksClub,https://avatars.githubusercontent.com/u/72699292?,started,...,None,None,None,None,None,None,None,None,None,<NA>
11,9349762982,WatchEvent,True,2026-05-12 07:02:22+00:00,72699292,DataTalksClub,,https://api.github.com/orgs/DataTalksClub,https://avatars.githubusercontent.com/u/72699292?,started,...,None,None,None,None,None,None,None,None,None,<NA>
12,9348454821,WatchEvent,True,2026-05-12 06:23:52+00:00,72699292,DataTalksClub,,https://api.github.com/orgs/DataTalksClub,https://avatars.githubusercontent.com/u/72699292?,started,...,None,None,None,None,None,None,None,None,None,<NA>
13,9347142649,WatchEvent,True,2026-05-12 05:37:10+00:00,72699292,DataTalksClub,,https://api.github.com/orgs/DataTalksClub,https://avatars.githubusercontent.com/u/72699292?,started,...,None,None,None,None,None,None,None,None,None,<NA>
14,9347073919,WatchEvent,True,2026-05-12 05:34:35+00:00,72699292,DataTalksClub,,https://api.github.com/orgs/DataTalksClub,https://avatars.githubusercontent.com/u/72699292?,started,...,None,None,None,None,None,None,None,None,None,<NA>
15,9346178057,WatchEvent,True,2026-05-12 04:58:55+00:00,72699292,DataTalksClub,,https://api.github.com/orgs/DataTalksClub,https://avatars.githubusercontent.com/u/72699292?,started,...,None,None,None,None,None,None,None,None,None,<NA>
16,9345205095,ForkEvent,True,2026-05-12 04:18:57+00:00,72699292,DataTalksClub,,https://api.github.com/orgs/DataTalksClub,https://avatars.githubusercontent.com/u/72699292?,forked,...,https://api.github.com/users/iragca/gists{/gis...,https://api.github.com/users/iragca/starred{/o...,https://api.github.com/users/iragca/subscriptions,https://api.github.com/users/iragca/orgs,https://api.github.com/users/iragca/repos,https://api.github.com/users/iragca/events{/pr...,https://api.github.com/users/iragca/received_e...,User,public,False
17,9343368464,WatchEvent,True,2026-05-12 02:54:54+00:00,72699292,DataTalksClub,,https://api.github.com/orgs/DataTalksClub,https://avatars.githubusercontent.com/u/72699292?,started,...,None,None,None,None,None,None,None,None,None,<NA>
18,9343289203,ForkEvent,True,2026-05-12 02:51:09+00:00,72699292,DataTalksClub,,https://api.github.com/orgs/DataTalksClub,https://avatars.githubusercontent.com/u/72699292?,forked,...,https://api.github.com/users/namle102/gists{/g...,https://api.github.com/users/namle102/starred{...,https://api.github.com/users/namle102/subscrip...,https://api.github.com/users/namle102/orgs,https://api.github.com/users/namle102/repos,https://api.github.com/users/namle102/events{/...,https://api.github.com/users/namle102/received...,User,public,False
19,9342848819,WatchEvent,True,2026-05-12 02:31:05+00:00,72699292,DataTalksClub,,https://api.github.com/orgs/DataTalksClub,https://avatars.githubusercontent.com/u/72699292?,started,...,None,None,None,None,None,None,None,None,None,<NA>
20,9338454172,WatchEvent,True,2026-05-11 23:19:41+00:00,72699292,DataTalksClub,,https://api.github.com/orgs/DataTalksClub,https://avatars.githubusercontent.com/u/72699292?,started,...,None,None,None,None,None,None,None,None,None,<NA>
21,9333208919,WatchEvent,True,2026-05-11 20:28:32+00:00,72699292,DataTalksClub,,https://api.github.com/orgs/DataTalksClub,https://avatars.githubusercontent.com/u/72699292?,started,...,None,None,None,None,None,None,None,None,None,<NA>
22,9330138591,WatchEvent,True,2026-05-11 19:19:25+00:00,72699292,DataTalksClub,,https://api.github.com/orgs/DataTalksClub,https://avatars.githubusercontent.com/u/72699292?,started,...,None,None,None,None,None,None,None,None,None,<NA>
23,9328368605,WatchEvent,True,2026-05-11 18:38:38+00:00,72699292,DataTalksClub,,https://api.github.com/orgs/DataTalksClub,https://avatars.githubusercontent.com/u/72699292?,started,...,None,None,None,None,None,None,None,None,None,<NA>
24,9328183600,ForkEvent,True,2026-05-11 18:34:10+00:00,72699292,DataTalksClub,,https://api.github.com/orgs/DataTalksClub,https://avatars.githubusercontent.com/u/72699292?,forked,...,https://api.github.com/users/IAN-RIUA/gists{/g...,https://api.github.com/users/IAN-RIUA/starred{...,https://api.github.com/users/IAN-RIUA/subscrip...,https://api.github.com/users/IAN-RIUA/orgs,https://api.github.com/users/IAN-RIUA/repos,https://api.github.com/users/IAN-RIUA/events{/...,https://api.github.com/users/IAN-RIUA/received...,User,public,False
25,9324714462,ForkEvent,True,2026-05-11 17:06:59+00:00,72699292,DataTalksClub,,https://api.github.com/orgs/DataTalksClub,https://avatars.githubusercontent.com/u/72699292?,forked,...,https://api.github.com/users/ngadoq/gists{/gis...,https://api.github.com/users/ngadoq/starred{/o...,https://api.github.com/users/ngadoq/subscriptions,https://api.github.com/users/ngadoq/orgs,https://api.github.com/users/ngadoq/repos,https://api.github.com/users/ngadoq/events{/pr...,https://api.github.com/users/ngadoq/received_e...,User,public,False
26,9323788884,WatchEvent,True,2026-05-11 16:44:41+00:00,72699292,DataTalksClub,,https://api.github.com/orgs/DataTalksClub,https://avatars.githubusercontent.com/u/72699292?,started,...,None,None,None,None,None,None,None,None,None,<NA>
27,9323355175,ForkEvent,True,2026-05-11 16:33:59+00:00,72699292,DataTalksClub,,https://api.github.com/orgs/DataTalksClub,https://avatars.githubusercontent.com/u/72699292?,forked,...,https://api.github.com/users/JunyongLee1217/gi...,https://api.github.com/users/JunyongLee1217/st...,https://api.github.com/users/JunyongLee1217/su...,https://api.github.com/users/JunyongLee1217/orgs,https://api.github.com/users/JunyongLee1217/repos,https://api.github.com/users/JunyongLee1217/ev...,https://api.github.com/users/JunyongLee1217/re...,User,public,False
28,9323340479,WatchEvent,True,2026-05-11 16:33:37+00:00,72699292,DataTalksClub,,https://api.github.com/orgs/DataTalksClub,https://avatars.githubusercontent.com/u/72699292?,started,...,None,None,None,None,None,None,None,None,None,<NA>
29,9322372800,ForkEvent,True,2026-05-11 16:10:20+00:00,72699292,DataTalksClub,,https://api.github.com/orgs/DataTalksClub,https://avatars.githubusercontent.com/u/72699292?,forked,...,https://api.github.com/users/officialpavanmand...,https://api.github.com/users/officialpavanmand...,https://api.github.com/users/officialpavanmand...,https://api.github.com/users/officialpavanmand...,https://api.github.com/users/officialpavanmand...,https://api.github.com/users/officialpavanmand...,https://api.github.com/users/officialpavanmand...,User,public,False