In [2]:
import pandas as pd

df = pd.read_csv("Walmart.csv", encoding_errors='ignore')

In [3]:
df.shape

(10051, 11)

In [4]:
df.head(5)

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [6]:
df.describe(include='all')

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
count,10051.000000,10051,10051,10051,10020,10020.000000,10051,10051,10051,10051.000000,10051.000000
unique,NaN,100,98,6,1008,NaN,1460,1001,3,NaN,NaN
top,NaN,WALM058,Weslaco,Fashion accessories,$63,NaN,01/12/21,15:48:00,Credit card,NaN,NaN
freq,NaN,240,399,4579,159,NaN,48,33,4260,NaN,NaN
mean,5025.741220,NaN,NaN,NaN,NaN,2.353493,NaN,NaN,NaN,5.825659,0.393791
std,2901.174372,NaN,NaN,NaN,NaN,1.602658,NaN,NaN,NaN,1.763991,0.090669
min,1.000000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,3.000000,0.180000
25%,2513.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,4.000000,0.330000
50%,5026.000000,NaN,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,6.000000,0.330000
75%,7538.500000,NaN,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,7.000000,0.480000
max,10000.000000,NaN,NaN,NaN,NaN,10.000000,NaN,NaN,NaN,10.000000,0.570000

In [7]:
df.dtypes

invoice_id          int64
Branch             object
City               object
category           object
unit_price         object
quantity          float64
date               object
time               object
payment_method     object
rating            float64
profit_margin     float64
dtype: object

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  object
 2   City            10051 non-null  object
 3   category        10051 non-null  object
 4   unit_price      10020 non-null  object
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  object
 7   time            10051 non-null  object
 8   payment_method  10051 non-null  object
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), object(7)
memory usage: 863.9+ KB

In [ ]:
# To find the all duplicates
df.duplicated().sum()

np.int64(51)

In [12]:
df.drop_duplicates(inplace=True)

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.isnull().sum()

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

In [15]:
# Remove the null values row from the tables
df.dropna(inplace=True)

In [16]:
df.isnull().sum()

invoice_id        0
Branch            0
City              0
category          0
unit_price        0
quantity          0
date              0
time              0
payment_method    0
rating            0
profit_margin     0
dtype: int64

In [ ]:
# The dataframe is decreased because we have drop the duplicates and null values
df.shape

(9969, 11)

In [18]:
df.columns

Index(['invoice_id', 'Branch', 'City', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin'],
      dtype='object')

In [ ]:
# We will get the error becuase of the $ sign
df['unit_price'].astype(float)

In [22]:
df['unit_price'] = df['unit_price'].str.replace('$', '')

In [23]:
df.head(5)

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [24]:
df['unit_price'] = df['unit_price'].astype(float)

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9969 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      9969 non-null   int64
 1   Branch          9969 non-null   object
 2   City            9969 non-null   object
 3   category        9969 non-null   object
 4   unit_price      9969 non-null   float64
 5   quantity        9969 non-null   float64
 6   date            9969 non-null   object
 7   time            9969 non-null   object
 8   payment_method  9969 non-null   object
 9   rating          9969 non-null   float64
 10  profit_margin   9969 non-null   float64
dtypes: float64(4), int64(1), object(6)
memory usage: 934.6+ KB

In [26]:
df['total'] = df['unit_price'] * df['quantity']
df.head(5)

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48,604.17

In [27]:
df.columns = df.columns.str.lower()
df.columns

Index(['invoice_id', 'branch', 'city', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin', 'total'],
      dtype='object')

In [ ]:
import sqlalchemy as sal

engine = sal.create_engine('mssql://writeyourSQLDashboardName/master?driver=writeYourSQLODBCDRIVER')

In [29]:
# Create a new database
import logging

logger = logging.getLogger(__name__)
new_db = 'walmart_db'

try:
    with engine.connect() as conn:
        conn.execution_options(isolation_level="AUTOCOMMIT")
        conn.execute(sal.text(f"CREATE DATABASE {new_db}"))
        logger.info("Data base has been created successful.")
except Exception as e:
    logger.error(f"Error occured while creating the database in SQL server data {e}")
    raise

In [ ]:
# Connect to your database

server = 'writeyourSQLDashboardName'
database = 'walmart_db'
driver = 'writeYourSQLODBCDRIVER'

engine = sal.create_engine(
    f"mssql+pyodbc://@{server}/{database}"
    f"?driver={driver}&trusted_connection=yes"
)

conn = engine.connect()

In [32]:
logging.basicConfig(
    level=logging.INFO,
    force=True
)
try:
    df.to_sql(
        'df_walmart',
        con=conn,
        index=False,
        if_exists='replace'
    )
    logger.info("Table has been created successfully in SQL database.")
except Exception as e:
    logger.error(f"Error occured while creating the table inside the database in SQL server data {e}")
    raise

INFO:__main__:Table has been created successfully in SQL database.